name: Check formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v4