name: Check formatting

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v4
