name: weeder

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      # NOTE: Each version of 'weeder' supports a specific version of GHC:
      #  * weeder-2.2.0 -> GHC 8.10.x
      #  * weeder-2.3.0 -> GHC 9.0.x
      #
      # It would be more trouble than it's worth for us to try and support the
      # full matrix of GHC <> weeder versions, and (in all likelihood) dead
      # code for one compiler version will be dead code in another.
      #
      # Since 'graphql-engine' is currently built with GHC 8.10.7, we'll stick
      # with 'weeder-2.2.0' here.
      #
      # TODO: We should add weeder-specific actions to the 'Makefile' rather
      # than relying on an environment variable.
      CABAL: cabal --project-file=./ci/weeder.project
    strategy:
      matrix:
        ghc: [ "8.10.7", "9.0.2" ]
        cabal: [ "latest" ] 

    steps:
      - name: Checkout this repository.
        uses: actions/checkout@v2

      - name: Set up Haskell tooling.
        uses: haskell/actions/setup@v1
        id: set-up-haskell-tooling
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Set up weeder store directory.
        id: set-up-weeder-store
        run: |
          mkdir -p $HOME/weeder-store

          cabal \
            --store-dir="${HOME}/weeder-store" \
            update \
            --project="./ci/${{ matrix.ghc }}/weeder.project"

          echo "::set-output name=weeder-store::${HOME}/weeder-store"

      - name: Cache weeder.
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.set-up-weeder-store.outputs.weeder-store }}
          key: ${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles("./ci/${{ matrix.ghc }}/weeder.project.freeze") }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles("./ci/${{ matrix.ghc }}/weeder.project.freeze") }}

      - name: Install weeder.
        id: set-up-weeder-store
        run: |
          cabal \
            --store-dir="${HOME}/weeder-store" \
            install \
            --project="./ci/${{ matrix.ghc }}/weeder.project" \
            weeder

      - name: Cache compiled dependency artifacts.
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.set-up-haskell-tooling.outputs.cabal-store }}
          key: ${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles("./ci/weeder.project.freeze") }}
          restore-keys: |
            ${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles("./ci/weeder.project.freeze") }}

      - name: Compile dependencies.
        run: |
          make update \
            PROJECT='ci/${{ matrix.ghc }}/ci.project'
          make build-deps \
            PROJECT='ci/${{ matrix.ghc }}/ci.project'

      - name: Compile library.
        run: |
          make build \
            PROJECT='ci/${{ matrix.ghc }}/ci.project'

      - name: Run weeder.
        run: |
          ${HOME}/.cabal/bin/weeder
